// SPDX-FileCopyrightText: 2026 Aurimas Niekis <aurimas@niekis.lt>
// SPDX-License-Identifier: GPL-3.0-or-later

// The desktop's icons by what they mean here, from the same Material Design
// Icons release its font is built from.
import {
  mdiAlert,
  mdiAlertCircle,
  mdiAntenna,
  mdiArrowDown,
  mdiArrowUp,
  mdiBackupRestore,
  mdiCameraOutline,
  mdiChartBellCurve,
  mdiChartGantt,
  mdiChartLine,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronRight,
  mdiClose,
  mdiCog,
  mdiDelete,
  mdiDownload,
  mdiFlagVariant,
  mdiGrid,
  mdiHistory,
  mdiInformation,
  mdiLogout,
  mdiMagnifyMinusOutline,
  mdiMagnifyPlusOutline,
  mdiMapMarker,
  mdiMenu,
  mdiOpenInNew,
  mdiPause,
  mdiPencil,
  mdiPlay,
  mdiPlus,
  mdiRadar,
  mdiRecordCircle,
  mdiRectangleOutline,
  mdiRefresh,
  mdiSpeedometer,
  mdiStar,
  mdiStarOutline,
  mdiStop,
  mdiTune,
  mdiViewGridOutline,
  mdiViewModuleOutline,
  mdiViewQuiltOutline,
  mdiViewSplitHorizontal,
  mdiViewSplitVertical,
  mdiWaterfall,
} from "@mdi/js";

export const icon = {
  menu: mdiMenu,
  device: mdiAntenna,
  range: mdiTune,
  analysis: mdiChartBellCurve,
  marker: mdiMapMarker,
  chart: mdiChartLine,
  waterfall: mdiWaterfall,
  zoomIn: mdiMagnifyPlusOutline,
  zoomOut: mdiMagnifyMinusOutline,
  resetZoom: mdiBackupRestore,
  record: mdiRecordCircle,
  snapshot: mdiCameraOutline,
  history: mdiHistory,
  performance: mdiSpeedometer,
  play: mdiPlay,
  stop: mdiStop,
  pause: mdiPause,
  reload: mdiRefresh,
  close: mdiClose,
  download: mdiDownload,
  delete: mdiDelete,
  settings: mdiCog,
  add: mdiPlus,
  edit: mdiPencil,
  star: mdiStar,
  starOff: mdiStarOutline,
  detach: mdiOpenInNew,
  up: mdiArrowUp,
  down: mdiArrowDown,
  expand: mdiChevronRight,
  collapse: mdiChevronDown,
  logout: mdiLogout,
  bands: mdiChartGantt,
  channels: mdiFlagVariant,
  detections: mdiRadar,
  layoutSingle: mdiRectangleOutline,
  layoutColumns: mdiViewSplitVertical,
  layoutRows: mdiViewSplitHorizontal,
  layoutThree: mdiViewQuiltOutline,
  layoutGrid: mdiViewGridOutline,
  layoutSix: mdiViewModuleOutline,
  layoutNine: mdiGrid,
  info: mdiInformation,
  success: mdiCheckCircle,
  warning: mdiAlert,
  error: mdiAlertCircle,
} as const;
