# Turns a directory of files into a C++ table the binary carries: path, bytes,
# MIME type and an ETag, as sweeppp::web::EmbeddedFile.
#
# Run as a script at build time, so an edited file reaches the binary on the
# next build rather than the next configure:
#
#   cmake -DDIR=<directory> -DOUTPUT=<file.cpp> -DFUNCTION=<qualified name>
#         [-DHEADER=<include>] -P EmbedFiles.cmake
#
# An empty or missing DIR writes a table with nothing in it, which is what a
# build without the web UI links.

if(NOT OUTPUT OR NOT FUNCTION)
    message(FATAL_ERROR "EmbedFiles.cmake needs OUTPUT and FUNCTION")
endif()

set(files "")
if(DIR AND IS_DIRECTORY "${DIR}")
    file(GLOB_RECURSE files RELATIVE "${DIR}" "${DIR}/*")
    list(SORT files)
endif()

string(REGEX REPLACE "::[^:]+$" "" namespace "${FUNCTION}")
string(REGEX REPLACE "^.*::" "" name "${FUNCTION}")

set(body "// Generated by cmake/EmbedFiles.cmake. Do not edit.\n\n")
if(HEADER)
    string(APPEND body "#include \"${HEADER}\"\n\n")
endif()
string(APPEND body "#include <array>\n#include <cstdint>\n#include <span>\n")
string(APPEND body "#include <sweeppp/web/WebServer.hpp>\n\n")
string(APPEND body "namespace ${namespace} {\nnamespace {\n\n")

set(entries "")
set(index 0)
foreach(file IN LISTS files)
    file(READ "${DIR}/${file}" hex HEX)
    file(SHA1 "${DIR}/${file}" sha)
    string(SUBSTRING "${sha}" 0 16 etag)
    string(LENGTH "${hex}" hexLength)
    math(EXPR size "${hexLength} / 2")
    if(size EQUAL 0)
        string(APPEND body "constexpr std::array<std::uint8_t, 1> kFile${index}{0};\n")
    else()
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
        string(APPEND body "constexpr std::array<std::uint8_t, ${size}> kFile${index}{${bytes}};\n")
    endif()
    string(APPEND entries
        "        sweeppp::web::EmbeddedFile{\"${file}\", std::span(kFile${index}).first(${size}),\n"
        "                                   sweeppp::web::mimeTypeFor(\"${file}\"), \"${etag}\"},\n")
    math(EXPR index "${index} + 1")
endforeach()

string(APPEND body "\n} // namespace\n\n")
string(APPEND body "std::span<const sweeppp::web::EmbeddedFile> ${name}() {\n")
if(index EQUAL 0)
    string(APPEND body "    return {};\n")
else()
    string(APPEND body "    static const std::array<sweeppp::web::EmbeddedFile, ${index}> files{\n")
    string(APPEND body "${entries}")
    string(APPEND body "    };\n    return files;\n")
endif()
string(APPEND body "}\n\n} // namespace ${namespace}\n")

# Written only when it changed, so an unchanged UI does not relink.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if(previous STREQUAL body)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${body}")
